### ISSUE TITLE
Output files not working for specific device setup

### ISSUE THREAD

**Issue by kdadzis** [nemocrys/multilog#35]
The procedures write_nomad_file() and write_metadata() lead to an unspecific FileNotFoundError: [WinError 2] for a minimal device setup on Windows (attached).  
[config.txt](https://github.com/nemocrys/multilog/files/10746053/config.txt)

**Comment by arvedes** [comment]
Can you please provide the log file?

A quick test on my windows laptop fails due to a missing [pyoptris installation](https://github.com/FiloCara/pyOptris#installation-guide). Did that work on yours?

**Comment by arvedes** [comment]
Update: I fixed #34, tested it with your configuration and it works well. Can you try again with the latest commit?

You have to add the following to your config files (with adjusted paths) in the Optris section
```yaml
library_path: C:/irDirectSDK/sdk/x64/libirimager.dll # Custom path to dll / so. Defaults to "/usr/lib/libirdirectsdk.so"
formats-path: C:/irDirectSDK  # Custom path to Formats.def. Defaults to "/usr/share/libirimager"
cali-path:  C:/irDirectSDK/cali # Custom path to calibration files. Defaults to "/usr/share/libirimager/cali"
```
